// Generated by tools/generate_fault_config.py; edit config/fault_manager.json.
#pragma once
#include "manager.h"
#include "subsystems.h"
namespace fm {
inline void loadPolicies(Manager& m) {
 {auto& p=m.policies[unsigned(Id::PI_OFFLINE)];
 p.remove=0;p.actions=0;
 p.severity=Severity::ADVISORY;p.ride=Ride::FULL;p.clear=Clear::AUTO_CLEAR;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::THERMAL_OFFLINE)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=8.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::THERMAL_BLIND)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::THERMAL_HOT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::EGT_SENSOR)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=8.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::COOLANT_SENSOR)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=8.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::MAT_SENSOR)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=8.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::MS3_OFFLINE)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::MAP_INVALID)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::IMU_FAULT)];
 p.remove=AIR_AUTO|AIR_MANUAL|TCS|AWC|LEAN|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::FRONT_WSS)];
 p.remove=AIR_AUTO|AIR_MANUAL|TCS|AWC|LEAN|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::REAR_WSS)];
 p.remove=AIR_AUTO|AIR_MANUAL|TCS|AWC|LEAN|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::DBW_FAULT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|FULL_DBW|TCS|AWC|LEAN;p.actions=CLOSE_AIR;
 p.severity=Severity::CRITICAL;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::WMI_FAILED)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::AIR_DRIVER)];
 p.remove=AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::AIR_STUCK)];
 p.remove=AIR_AUTO|AIR_MANUAL|HIGH_BOOST;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG;
 p.severity=Severity::CRITICAL;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::SERVICE_CLEAR;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::FUEL_DP_LOW)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::FUEL_DP_CRITICAL)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW|FULL_RPM;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG|ECU_PROTECT_REQUEST;
 p.severity=Severity::CRITICAL;p.ride=Ride::ENGINE_PROTECT;p.clear=Clear::SERVICE_CLEAR;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::OIL_LOW)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::STOP_REQUIRED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=0.0f;p.boost=0.0f;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::OIL_CRITICAL)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW|FULL_RPM;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG|ECU_PROTECT_REQUEST;
 p.severity=Severity::CRITICAL;p.ride=Ride::ENGINE_PROTECT;p.clear=Clear::SERVICE_CLEAR;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::EWG_LEFT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::EWG_RIGHT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::OVERBOOST)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::BOOST_UNCONTAINED)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL|WMI_POWER|FULL_DBW|FULL_RPM;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG|ECU_PROTECT_REQUEST;
 p.severity=Severity::CRITICAL;p.ride=Ride::ENGINE_PROTECT;p.clear=Clear::SERVICE_CLEAR;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::CHARGING)];
 p.remove=NORMAL_LOAD;p.actions=SHED_OPTIONAL|STOP_COMPRESSOR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::COOLING)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=FAN_MAX|CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::LAMBDA_LEFT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::LAMBDA_RIGHT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::CYLINDER_LEFT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::CYLINDER_RIGHT)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::KNOCK)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
 {auto& p=m.policies[unsigned(Id::TURBO_OVERSPEED)];
 p.remove=HIGH_BOOST|AIR_AUTO|AIR_MANUAL;p.actions=CLOSE_AIR|ISOLATE_AIR|STOP_COMPRESSOR|OPEN_EWG;
 p.severity=Severity::WARNING;p.ride=Ride::DEGRADED;p.clear=Clear::CLEAR_AFTER_STABLE;
 p.confirm_ms=0;p.recover_ms=0;p.recovery_configured=false;
 p.torque=NAN;p.boost=NAN;p.rpm=NAN;}
}
inline void loadMonitors(SubsystemMonitors& m) {
m.fuel_fusion_enabled=false;
m.oil.rpm[0]=NAN;m.oil.minimum[0]=NAN;
m.oil.rpm[1]=NAN;m.oil.minimum[1]=NAN;
m.oil.rpm[2]=NAN;m.oil.minimum[2]=NAN;
m.oil.rpm[3]=NAN;m.oil.minimum[3]=NAN;
m.oil.reference_temp=NAN;
m.oil.temp_slope=NAN;
}
constexpr bool master_isolation_configured=false;
}
