"""Generate the embedded inhibit matrix from the shared service configuration."""
from pathlib import Path
import json,sys,math,re
ROOT=Path(__file__).resolve().parents[1]
def validate(config):
    headers=ROOT/'arduino/teensy41/albatross_controller_teensy41/fault_manager'
    declarations=(headers/'types.h').read_text()+(headers/'subsystems.h').read_text()
    def members(name):
        body=re.search(r'enum(?: class)? '+name+r':\w+\s*\{([^}]+)\}',declarations).group(1)
        return [item.strip().split('=')[0] for item in body.split(',') if item.strip()!='COUNT']
    def timer(value,nullable=False):
        if nullable and value is None:return
        if type(value) is not int or not 0<=value<2**31:raise ValueError('invalid timer')
    if [r['id'] for r in config['rules']]!=members('Id'):raise ValueError('registry must preserve wire ID order')
    for r in config['rules']:
        for field,enum in (('severity','Severity'),('ride','Ride'),('clear','Clear')):
            if r[field] not in members(enum):raise ValueError('invalid '+field)
        for field,enum in (('remove','Capability'),('actions','Action')):
            if not isinstance(r[field],list) or any(v not in members(enum) for v in r[field]):raise ValueError('invalid '+field)
        timer(r['confirm_ms']);timer(r['recover_ms'],True)
    for r in config['monitors'].values():
        for field in ('enabled','context_verified','high','require_running'):
            if type(r[field]) is not bool:raise ValueError('invalid monitor boolean')
        for field,enum in (('fault','Id'),('a','Channel'),('b','Channel'),('operation','Operation')):
            if r[field] not in members(enum):raise ValueError('invalid monitor '+field)
        timer(r['confirm_ms'],not r['enabled'])
    oil=config['oil_envelope']
    if len(oil['rpm_axis'])!=4 or len(oil['minimum_psi'])!=4:raise ValueError('oil envelope requires four points')
    if any(r['enabled'] and r['operation']=='OIL_ERROR' for r in config['monitors'].values()):
        if any(v is None for v in oil['rpm_axis']+oil['minimum_psi']+[oil['reference_temp_c'],oil['temp_slope_psi_per_c']]):raise ValueError('oil envelope incomplete')
        if any(a>=b for a,b in zip(oil['rpm_axis'],oil['rpm_axis'][1:])):raise ValueError('oil RPM axis must increase')
    for field in ('active_high','driver_verified','closure_feedback_verified'):
        if type(config['master_air_isolation'][field]) is not bool:raise ValueError('invalid hardware boolean')

def generate(config=None):
    if config is None:config=json.loads((ROOT/'config/fault_manager.json').read_text())
    validate(config)
    lines=['// Generated by tools/generate_fault_config.py; edit config/fault_manager.json.', '#pragma once', '#include "manager.h"', '#include "subsystems.h"', 'namespace fm {', 'inline void loadPolicies(Manager& m) {']
    def number(value):
        if value is None:return 'NAN'
        if type(value) not in (int,float) or not math.isfinite(value) or value<0:raise ValueError('invalid limit')
        return str(float(value))+'f'
    for r in config['rules']:
        if r['torque'] is not None and not 0<=r['torque']<=1:raise ValueError('torque must be 0..1')
        for field in ('confirm_ms','recover_ms'):
            v=r[field]
            if v is not None and (not isinstance(v,int) or not 0<=v<2**31):raise ValueError('invalid timer')
        lines += [' {auto& p=m.policies[unsigned(Id::'+r['id']+')];',
            ' p.remove='+('|'.join(r['remove']) or '0')+';p.actions='+('|'.join(r['actions']) or '0')+';',
            ' p.severity=Severity::'+r['severity']+';p.ride=Ride::'+r['ride']+';p.clear=Clear::'+r['clear']+';',
            f" p.confirm_ms={r['confirm_ms']};p.recover_ms={r['recover_ms'] or 0};p.recovery_configured={str(r['recover_ms'] is not None).lower()};",
            ' p.torque='+number(r['torque'])+';p.boost='+number(r['boost'])+';p.rpm='+number(r['rpm'])+';}']
    if type(config['fuel_fusion_enabled']) is not bool:raise ValueError('invalid fusion enable')
    if config['fuel_fusion_enabled']:
        required=('fuel_dp','lambda_left','lambda_right','fuel_dp_critical')
        if any(not config['monitors'].get(k,{}).get('enabled',False) for k in required):
            raise ValueError('fuel fusion requires commissioned pressure and dual lambda monitors')
    lines+=['}', 'inline void loadMonitors(SubsystemMonitors& m) {',
            'm.fuel_fusion_enabled='+str(config['fuel_fusion_enabled']).lower()+';']
    for n,r in enumerate(config['monitors'].values()):
        if n>=32:raise ValueError('too many monitors')
        if not r['enabled']:continue
        if not r['context_verified'] or any(r[k] is None for k in ('trip','clear','confirm_ms')):raise ValueError('uncommissioned monitor')
        # Signed thresholds are required for falling-pressure rates/error bands.
        for k in ('trip','clear'):
            if not math.isfinite(r[k]):raise ValueError('nonfinite threshold')
        if (r['high'] and r['clear']>r['trip']) or (not r['high'] and r['clear']<r['trip']):raise ValueError('reversed hysteresis')
        lines += [f' {{auto& r=m.rules[{n}];r.enabled=true;r.fault=Id::{r["fault"]};r.a=Channel::{r["a"]};r.b=Channel::{r["b"]};',
                  f'r.operation=Operation::{r["operation"]};r.band.trip={float(r["trip"])}f;r.band.clear={float(r["clear"])}f;r.band.high={str(r["high"]).lower()};',
                  f'r.confirm_ms={r["confirm_ms"]};r.require_running={str(r["require_running"]).lower()};}}']
    oil=config['oil_envelope']
    for n in range(4):lines += [f'm.oil.rpm[{n}]={number(oil["rpm_axis"][n])};m.oil.minimum[{n}]={number(oil["minimum_psi"][n])};']
    lines += ['m.oil.reference_temp='+number(oil['reference_temp_c'])+';']
    slope=oil['temp_slope_psi_per_c']
    if slope is not None and not math.isfinite(slope):raise ValueError('invalid oil slope')
    hardware=config['master_air_isolation']
    if hardware['pin'] not in (None,12):raise ValueError('Only reclaimed legacy pin 12 has been reviewed for master isolation')
    if not hardware['active_high']:raise ValueError('Master driver must be active-high with external pulldown')
    lines += ['m.oil.temp_slope='+('NAN' if slope is None else str(float(slope))+'f')+';', '}',
              'constexpr bool master_isolation_configured='+str(hardware['pin']==12 and hardware['driver_verified']).lower()+';', '}','']
    return '\n'.join(lines)
if __name__=='__main__':
    path=ROOT/'arduino/teensy41/albatross_controller_teensy41/fault_manager/policies.h'
    result=generate()
    if '--check' in sys.argv:
        assert path.read_text()==result,'fault policies out of date'
    else:path.write_text(result)
