"""Generate thermal sensor/calibration/hardware constants; --check detects drift."""
import argparse
import binascii
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FW = ROOT/'arduino/teensy41/albatross_thermal_node'

def outputs():
    cfg=json.loads((ROOT/'config/thermal_system.json').read_text())
    a=cfg['acquisition']; ads=a['ads1115']; rtd=a['max31865']
    assert [s['id'] for s in cfg['sensors']]==list(range(1,33))
    assert [a['spi'][k] for k in ('mosi','miso','sck')]==[11,12,13], 'Driver uses default SPI pins'
    assert len(a['spi']['tc_cs'])==4
    assert all(0x48<=b['address']<=0x4b for b in ads['boards'])
    assert 1<=a['recovery_samples']<=255
    assert rtd['reference_ohm']==cfg['calibration_profiles']['pt1000']['reference_ohm']
    assert rtd['nominal_ohm']==cfg['calibration_profiles']['pt1000']['r0_ohm']
    assert len(ads['boards'])==5 and len(a['spi']['rtd_cs'])==7
    assert len(set((b['bus'],b['address']) for b in ads['boards']))==5
    pins=[a['spi'][k] for k in ('mosi','miso','sck')]+a['spi']['tc_cs']+a['spi']['rtd_cs']+[18,19,17,16,22,23]
    assert len(pins)==len(set(pins))
    assert [(b['bus'],b['sda'],b['scl']) for b in ads['boards']]==[(0,18,19)]*3+[(1,17,16)]*2
    assert ads['full_scale_v']==4.096 and ads['data_rate_sps']==860, 'Update register encoding with range/rate'
    assert all(w in (2,3,4) for w in rtd['lead_wires']) and len(rtd['lead_wires'])==7
    assert ads['excitation_channel']==18
    rows=[]; used=set()
    tech={'k_type':'K_TYPE','iat_ntc':'IAT_NTC','iat_ntc_high':'IAT_NTC','coolant_ntc':'COOLANT_NTC','pt1000':'PT1000','disabled':'DISABLED'}
    def f(v):return f'{float(v)}f'
    for s in cfg['sensors']:
        p=cfg['calibration_profiles'][s['technology']];src=s['source']
        if s['enabled']:
            key=(src['bus'],src['channel']);assert key not in used;used.add(key)
        vals=[str(s['id']),json.dumps(s['key']),'SensorTechnology::'+tech[s['technology']],'SourceBus::'+src['bus'].upper(),str(src['channel']),str(round(1000/s['sample_hz'])),str(round(1000/s['report_hz'])),f(s['filter_tau_s']),f(s['derivative_tau_s']),f(s['valid_c'][0]),f(s['valid_c'][1]),str(s['valid_raw'][0]),str(s['valid_raw'][1]),str(s['enabled']).lower()]+[f(p.get(k,0)) for k in ('pullup_ohm','r0_ohm','t0_c','beta_k')]
        rows.append('  {'+', '.join(vals)+'},')
    assert {c for b,c in used if b=='ads1115'}==set(range(18))
    assert {c for b,c in used if b=='max31856'}==set(range(4))
    assert {c for b,c in used if b=='max31865'}==set(range(7))
    sensor='#include "sensor_config.h"\n// Generated by tools/generate_thermal_config.py; edit shared JSON.\nconst SensorConfig SENSOR_CONFIG[THERMAL_SENSOR_COUNT] = {\n'+'\n'.join(rows)+'\n};\n'
    h=['#pragma once','#include <stdint.h>','// Generated hardware allocation and driver timing, not earned vehicle calibration.','namespace ThermalHardware {']
    for name,values in [('TC_CS',a['spi']['tc_cs']),('RTD_CS',a['spi']['rtd_cs']),('RTD_WIRES',rtd['lead_wires']),('ADC_BUS',[b['bus'] for b in ads['boards']]),('ADC_ADDRESS',[b['address'] for b in ads['boards']])]:
        h.append(f'constexpr uint8_t {name}[] = {{'+','.join(map(str,values))+'};')
    for name,val in [('STALE_MS',ads['stale_ms']),('RETRY_MS',ads['retry_ms']),('ADC_TIMEOUT_MS',ads['conversion_timeout_ms']),('I2C_HZ',ads['clock_hz']),('RTD_BIAS_MS',rtd['bias_settle_ms']),('RTD_CONVERSION_MS',rtd['conversion_ms']),('RTD_PERIOD_MS',rtd['period_ms']),('RECOVERY_SAMPLES',a['recovery_samples'])]:
        h.append(f'constexpr uint32_t {name} = {val};')
    p=cfg['calibration_profiles']['pt1000']
    for name,val in [('ADC_LSB_V',ads['full_scale_v']/32768),('RTD_RREF',rtd['reference_ohm']),('RTD_R0',rtd['nominal_ohm']),('RTD_A',p['a']),('RTD_B',p['b']),('RTD_C',p['c'])]:h.append(f'constexpr float {name} = {f(val)};')
    # Canonical CRC avoids platform newline differences; Pi configuration file is identical logically.
    crc=binascii.crc32(json.dumps(cfg,sort_keys=True,separators=(',',':')).encode())&0xffffffff
    h.append(f'constexpr uint32_t CONFIG_CRC32 = 0x{crc:08X}UL;')
    h.append('}')
    return {FW/'sensor_config.cpp':sensor,FW/'thermal_hardware.h':'\n'.join(h)+'\n'}

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    for path,content in outputs().items():
        if args.check:assert path.read_text()==content, f'Stale generated file: {path}'
        else:path.write_text(content,encoding='utf-8')
    print('PASS thermal generated configuration / pin and channel uniqueness')
if __name__=='__main__':main()
